apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config-{{ .Release.Name }}
data:
  rclone.conf: |
{{ .Values.rcloneConf | indent 4 }}
  include-pattern.conf: |
{{ .Values.includePattern | indent 4 }}
