{{- define "producer-app.podTemplate" -}}
{{- $root := . -}}
metadata:
{{- if .Values.podAnnotations }}
  annotations:
  {{- range $key, $value := .Values.podAnnotations }}
    {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    app: {{ template "producer-app.name" . }}
    release: {{ .Release.Name }}
    {{- range $key, $value := .Values.podLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  {{- if not .Values.deployment }}
  restartPolicy: {{ .Values.restartPolicy }}
  {{- end }}
  {{- if .Values.serviceAccountName }}
  serviceAccountName: {{ .Values.serviceAccountName }}
  {{- end }}
  {{- if .Values.tolerations }}
  tolerations:
{{ toYaml .Values.tolerations | indent 4 }}
  {{- end }}
  affinity:
    {{- if .Values.nodeAffinity }}
    nodeAffinity:
{{ toYaml .Values.nodeAffinity | indent 6 }}
    {{- end }}
  {{- if .Values.imagePullSecrets }}
  imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
  {{- end }}
  containers:
  - name: {{ template "producer-app.name" . }}
    image: "{{ .Values.image }}:{{ .Values.imageTag }}"
    imagePullPolicy: "{{ .Values.imagePullPolicy }}"
    resources:
{{ toYaml .Values.resources | indent 6 }}
    env:
      - name: ENV_PREFIX
        value: {{ .Values.configurationEnvPrefix }}_
      {{- range $key, $value := .Values.streams.config }}
      - name: {{ printf "STREAMS_%s" $key | replace "." "_" | upper | quote }}
        value: {{ $value | quote }}
        {{- end }}
        {{- if hasKey .Values.streams "brokers" }}
      - name: "{{ .Values.configurationEnvPrefix }}_BROKERS"
        value: {{ .Values.streams.brokers | quote }}
        {{- end }}
        {{- if hasKey .Values.streams "schemaRegistryUrl" }}
      - name: "{{ .Values.configurationEnvPrefix }}_SCHEMA_REGISTRY_URL"
        value: {{ .Values.streams.schemaRegistryUrl | quote }}
        {{- end }}
        {{- if hasKey .Values "debug" }}
      - name: "{{ .Values.configurationEnvPrefix }}_DEBUG"
        value: {{ .Values.debug | quote }}
        {{- end }}
        {{- if hasKey .Values.streams "outputTopic" }}
      - name: "{{ .Values.configurationEnvPrefix }}_OUTPUT_TOPIC"
        value: {{ .Values.streams.outputTopic | quote }}
        {{- end }}
        {{- if and (hasKey .Values.streams "extraOutputTopics") (.Values.streams.extraOutputTopics) }}
      - name: "{{ .Values.configurationEnvPrefix }}_EXTRA_OUTPUT_TOPICS"
        value: "{{- range $key, $value := .Values.streams.extraOutputTopics }}{{ $key }}={{ $value }},{{- end }}"
        {{- end }}
        {{- range $key, $value := .Values.secrets }}
      - name: "{{ $key }}"
        valueFrom:
          secretKeyRef:
            name: {{ template "producer-app.fullname" $ }}
            key: "{{ $key }}"
        {{- end }}
        {{- range $key, $value := .Values.secretRefs }}
      - name: "{{ $key }}"
        valueFrom:
          secretKeyRef:
            name: {{ $value.name }}
            key: "{{ $value.key }}"
        {{- end }}
        {{- range $key, $value := .Values.commandLine }}
      - name: "{{ $root.Values.configurationEnvPrefix }}_{{ $key }}"
        value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := .Values.env }}
      - name: {{ $key | quote }}
        value: {{ $value | quote }}
        {{- end }}
      - name: JAVA_TOOL_OPTIONS
        value: '-XX:MaxRAMPercentage={{ printf "%.1f" .Values.javaOptions.maxRAMPercentage }}
                {{ .Values.javaOptions.others | join " " }}'
    {{- range .Values.ports }}
    ports:
      - containerPort: {{ .containerPort }}
        name: {{ .name | quote }}
        {{- if .protocol }}
        protocol: {{ .protocol | quote }}
        {{- end }}
    {{- end }}
    {{- if .Values.livenessProbe }}
    livenessProbe:
    {{- .Values.livenessProbe | toYaml | nindent 6 }}
    {{- end }}
    {{- if .Values.readinessProbe }}
    readinessProbe:
    {{- .Values.readinessProbe | toYaml | nindent 6 }}
    {{- end }}
{{- end -}}
