apiVersion: v1
name: rclone-copy
description: A helm chart for rclone copy on Kubernetes.
version: 0.1.1-SNAPSHOT
maintainers:
  - name: bakdata
    email: opensource@bakdata.com
    url: bakdata.com
