{{- $root := . -}}
{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .name }}
  {{- if $root.Values.namespace }}
  namespace: {{ $root.Values.namespace }}
  {{- end }}
  labels:
    strimzi.io/cluster: {{ $root.Values.strimziCluster }}
    {{- range $key, $value := $root.Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
    {{ include "kafka-topics.labels" $ | nindent 4 }}
spec:
  {{- toYaml .spec | nindent 2 }}
  {{- if and (not .spec.partitions) ($root.Values.partitions) }}
  partitions: {{ $root.Values.partitions }}
  {{- end }}
  {{- if and (not .spec.replicas) ($root.Values.replicas) }}
  replicas: {{ $root.Values.replicas }}
  {{- end }}
   {{- if and (not .spec.config) ($root.Values.config) }}
  config: 
    {{- toYaml $root.Values.config | nindent 4}}
  {{- end }}
---
{{- end }}
