{{ if .Values.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "streams-app-cleanup-job.name" . }}
data:
  {{- range $key, $value := .Values.files }}
  {{ $key }}: {{ $value.content | nindent 4 }}
  {{- end }}
{{ end }}
