site_name: streams-bootstrap
repo_url: https://github.com/bakdata/streams-bootstrap
repo_name: bakdata/streams-bootstrap
site_url: https://bakdata.github.io/streams-bootstrap/

theme:
  name: material

nav:
  - Home: markdown.md
