site_name: streams-bootstrap
repo_url: https://github.com/bakdata/streams-bootstrap
repo_name: bakdata/streams-bootstrap
site_url: https://bakdata.github.io/streams-bootstrap/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - versioning
extra:
  version:
    provider: mike
plugins:
  - search
nav:
  - Index: index.md
  - Javadoc:
       - streams-bootstrap-cli: javadoc/streams-bootstrap-bom/index.html
       - streams-bootstrap-cli: javadoc/streams-bootstrap-cli/index.html
       - streams-bootstrap-cli: javadoc/streams-bootstrap-cli-test/index.html
       - streams-bootstrap-cli: javadoc/streams-bootstrap-core/index.html
       - streams-bootstrap-cli: javadoc/streams-bootstrap-large-messages/index.html
       - streams-bootstrap-cli: javadoc/streams-bootstrap-test/index.html
