site_name: streams-bootstrap
site_url: https://bakdata.github.io/streams-bootstrap/
repo_name: streams-bootstrap
repo_url: https://github.com/bakdata/streams-bootstrap
remote_branch: gh-pages
copyright: Copyright &copy; 2025 bakdata

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - versioning
extra:
  version:
    provider: mike
plugins:
  - search
  - mike:
      alias_type: symlink
markdown_extensions:
  - attr_list
nav:
  - User guide:
      - What is streams-bootstrap: index.md
      - Changelog: user/changelog.md
      - Getting Started:
          - Setup: user/getting-started/setup.md
          - Quick start: user/getting-started/quick-start.md
      - Concepts:
          - General concepts: user/concepts/general.md
          - Streams concepts: user/concepts/streams.md
          - Producer concepts: user/concepts/producer.md
      - Deployment:
          - Local deployment: user/deployment/local.md
          - Kubernetes: user/deployment/kubernetes.md
      - Examples:
          - ATM Fraud detection pipeline: user/examples/atm-fraud-pipeline.md
  - Javadoc: javadoc/index.html
