{{- $root := . -}}

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "streams-app.fullname" . }}
  labels:
    app: {{ template "streams-app.name" . }}
    chart: {{ template "streams-app.chart" . }}
    release: {{ .Release.Name }}
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 30
  template:
    metadata:
    {{- if or .Values.awsRole .Values.annotations }}
      annotations:
      {{- if .Values.awsRole }}
        iam.amazonaws.com/role: {{ .Values.awsRole }}
      {{- end }}
      {{- range $key, $value := .Values.annotations }}
        {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    {{- end }}
      labels:
        app: {{ template "streams-app.name" . }}
        release: {{ .Release.Name }}
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      restartPolicy: {{ .Values.cleanup.restartPolicy }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      affinity:
        {{- if .Values.nodeAffinity }}
        nodeAffinity:
{{ toYaml .Values.nodeAffinity | indent 10 }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "streams-app.name" . }}
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: ENV_PREFIX
              value: {{ .Values.configurationEnvPrefix }}_
            {{- range $key, $value := .Values.streams.config }}
            - name: {{ printf "STREAMS_%s" $key | replace "." "_" | upper | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "brokers" }}
            - name: "{{ .Values.configurationEnvPrefix }}_BROKERS"
              value: {{ .Values.streams.brokers | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "schemaRegistryUrl" }}
            - name: "{{ .Values.configurationEnvPrefix }}_SCHEMA_REGISTRY_URL"
              value: {{ .Values.streams.schemaRegistryUrl | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "productive" }}
            - name: "{{ .Values.configurationEnvPrefix }}_PRODUCTIVE"
              value: {{ .Values.streams.productive | quote }}
            {{- end }}
            {{- if hasKey .Values "debug" }}
            - name: "{{ .Values.configurationEnvPrefix }}_DEBUG"
              value: {{ .Values.debug | quote }}
            {{- end }}
            - name: "{{ .Values.configurationEnvPrefix }}_CLEAN_UP"
              value: "true"
            {{- if hasKey .Values.cleanup "deleteOutput" }}
            - name: "{{ .Values.configurationEnvPrefix }}_DELETE_OUTPUT"
              value: {{ .Values.cleanup.deleteOutput | quote }}
            {{- end }}
            {{- if and (hasKey .Values.streams "inputTopics") (.Values.streams.inputTopics) }}
            - name: "{{ .Values.configurationEnvPrefix }}_INPUT_TOPICS"
              value: {{ .Values.streams.inputTopics | join "," | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "inputPattern" }}
            - name: "{{ .Values.configurationEnvPrefix }}_INPUT_PATTERN"
              value: {{ .Values.streams.inputPattern | join "," | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "outputTopic" }}
            - name: "{{ .Values.configurationEnvPrefix }}_OUTPUT_TOPIC"
              value: {{ .Values.streams.outputTopic | quote }}
            {{- end }}
            {{- if hasKey .Values.streams "errorTopic" }}
            - name: "{{ .Values.configurationEnvPrefix }}_ERROR_TOPIC"
              value: {{ .Values.streams.errorTopic | quote }}
            {{- end }}
            {{- if and (hasKey .Values.streams "extraOutputTopics") (.Values.streams.extraOutputTopics) }}
            - name: "{{ .Values.configurationEnvPrefix }}_EXTRA_OUTPUT_TOPICS"
              value: "{{- range $key, $value := .Values.streams.extraOutputTopics }}{{ $key }}={{ $value }},{{- end }}"
            {{- end }}
            {{- $delimiter := ";" }}
            {{- if and (hasKey .Values.streams "extraInputTopics") (.Values.streams.extraInputTopics) }}
            - name: "{{ .Values.configurationEnvPrefix }}_EXTRA_INPUT_TOPICS"
              value: "{{- range $key, $value := .Values.streams.extraInputTopics }}{{ $key }}={{ $value | join $delimiter }},{{- end }}"
            {{- end }}
            {{- if and (hasKey .Values.streams "extraInputPatterns") (.Values.streams.extraInputPatterns) }}
            - name: "{{ .Values.configurationEnvPrefix }}_EXTRA_INPUT_PATTERNS"
              value: "{{- range $key, $value := .Values.streams.extraInputPatterns }}{{ $key }}={{ $value }},{{- end }}"
            {{- end }}
            {{- range $key, $value := .Values.secrets }}
            - name: "{{ $key }}"
              valueFrom:
                secretKeyRef:
                  name: {{ template "streams-app.fullname" $ }}
                  key: "{{ $key }}"
            {{- end }}
            {{- range $key, $value := .Values.secretRefs }}
              - name: "{{ $key }}"
                valueFrom:
                  secretKeyRef:
                    name: {{ $value.name }}
                    key: "{{ $value.key }}"
            {{- end }}
            {{- range $key, $value := .Values.commandLine }}
            - name: "{{ $root.Values.configurationEnvPrefix }}_{{ $key }}"
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            - name: JAVA_TOOL_OPTIONS
              value: '-XX:MaxRAMPercentage={{ printf "%.1f" .Values.javaOptions.maxRAMPercentage }}
                {{ .Values.javaOptions.others | join " " }}'
  backoffLimit: {{ .Values.cleanup.backoffLimit }}
