{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "streams-app-cleanup-job.fullname" . }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
    type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
