{{ if .Values.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "streams-app.name" . }}
  {{- include "streams-app.default-annotations" . }}
data:
  {{- range $key, $value := .Values.files }}
  {{ $key }}: {{ $value.content | quote }}
  {{- end }}
{{ end }}
