{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "streams-app.name" . }}-jmx-configmap
  {{- include "streams-app.annotations" . }}
  labels:
    {{- include "streams-app.labels" . | nindent 4 }}
data:
  jmx-kafka-streams-app-prometheus.yml: |+
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      {{- range .Values.jmx.metricRules}}
      - pattern: {{ . | quote }}
      {{- end}}
{{- end }}
