{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "streams-app.name" . }}-jmx-configmap
  {{- include "streams-app.annotations" . }}
  labels:
    app: {{ template "streams-app.name" . }}
    chart: {{ template "streams-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  jmx-kafka-streams-app-prometheus.yml: |+
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules: {{ toYaml .Values.prometheus.jmx.metricRules | nindent 4 }}
{{- end }}
