apiVersion: v1
name: producer-app
description: A helm chart for deploying a Kafka producer application based on the bakdata KafkaProducerApplication template.
version: 0.1.1-SNAPSHOT
maintainers:
  - name: bakdata
    email: opensource@bakdata.com
    url: bakdata.com
