nameOverride: bakdata-producer-app

image: producerApp
imageTag: latest
imagePullPolicy: Always

imagePullSecrets: [ ]

restartPolicy: OnFailure

configurationEnvPrefix: "APP"

#awsRole: my-aws-role

# Optional: Cron schedule for this producer job
# schedule: "0 12 * * *"

suspend: false

tolerations: [ ]
#   - key: "foo"
#     operator: "Exists"
#     effect: "NoSchedule"
#   - key: "bar"
#     operator: "Exists"
#     effect: "NoSchedule"

nodeAffinity: { }
#   requiredDuringSchedulingIgnoredDuringExecution:
#     nodeSelectorTerms:
#     - matchExpressions:
#       - key: foo
#         operator: In
#         values:
#         - bar
#         - baz
#   preferredDuringSchedulingIgnoredDuringExecution:
#   - weight: 1
#     preference:
#       matchExpressions:
#       - key: foo
#         operator: In
#         values:
#         - bar
#         - baz

resources:
  requests:
    cpu: 200m
    memory: 300Mi
  limits:
    memory: 2G
    cpu: 500m

streams:
#  brokers: "test:9092"
#  schemaRegistryUrl: "url:1234"
  config: {}
#    max.poll.records: 500
#    Note that YAML may convert large integers to scientific notation. Use Strings to avoid this.
#    max.request.size: "1000000"
#  outputTopic: output
  extraOutputTopics: {}
#   role: output

commandLine: { }
#  MY_CLI_PARAM: "foo-bar"

debug: false

env: { }
#  MY_ENV_VARIABLE: foo-bar

secrets: { }
#  MY_SECRET: fo-bar

annotations: { }
#  MY_ANNOTATION: "foo-bar"

labels: { }
#  MY_LABEL: "foo-bar"

javaOptions:
  maxRAMPercentage: 75
  others: [ ]
#   - "-XX:MinRAMPercentage=50.0"

successfulJobsHistoryLimit: 1
failedJobsHistoryLimit: 1
backoffLimit: 6
#ttlSecondsAfterFinished: 100
