name: "Update documentation in gh-pages (dev)"

inputs:
  username:
    description: "GitHub username"
    required: true
  email:
    description: "GitHub email"
    required: true
  token:
    description: "GitHub Token (must be a PAT for repository dispatch)"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v1
      with:
        python-version: 3.11

    - name: Extract Javadoc JARs into docs/javadoc
      shell: bash
      run: |
        MODULES=("streams-bootstrap-cli")
        mkdir -p docs/javadoc
        for module in "${MODULES[@]}"; do
          echo "Looking for javadoc jar in $module..."
          jar_path=$(find "$module/build/libs" -type f -name '*-javadoc.jar' | sort | tail -n 1)
          if [ -z "$jar_path" ]; then
            echo "No javadoc jar found for $module"
            continue
          fi
          target_dir="docs/javadoc/$module"
          mkdir -p "$target_dir"
          echo "Extracting $jar_path to $target_dir"
          unzip -q "$jar_path" -d "$target_dir"
        done

    - name: Update documentation branch with mike
      shell: bash
      run: |
        pip install -r ./docs/requirements.txt
        git config --local user.name  ${{ inputs.username }}
        git config --local user.email ${{ inputs.email }}
        git config --local user.password ${{ inputs.token }}
        git fetch origin gh-pages

        mike deploy dev --push --rebase --config-file ./docs/mkdocs.yml
