name: Deploy Wiki to GitHub Pages

on:
  push:
    branches:
      - 'feature/wiki-gh-pages'
    tags:
      - '**'

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry and dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH
          poetry install --with docs

      - name: Deploy docs
        run: |
          poetry run mkdocs gh-deploy --config-file docs/mkdocs.yml --clean --force
