- name: Checkout
  uses: actions/checkout@v4
  with:
    fetch-depth: 0

- name: Install Poetry and dependencies
  run: |
    curl -sSL https://install.python-poetry.org | python3 -
    echo "${HOME}/.local/bin" >> $GITHUB_PATH
    poetry install --with docs

- name: Sync gh-pages branch locally
  run: |
    git fetch origin gh-pages:gh-pages || git checkout --orphan gh-pages
    git reset --hard origin/gh-pages || true

- name: Deploy docs
  run: |
    poetry run mkdocs gh-deploy --config-file docs/mkdocs.yml --clean --force
